from nvcr.io/nvidia/pytorch:21.10-py3
#from nvcr.io/nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04

RUN apt-get update && apt-get install -y apt-utils && rm -rf /var/lib/apt/lists/*

# Set the locale
RUN  apt-get update && apt-get install locales && locale-gen en_US.UTF-8 && rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
               tzdata libxml2-dev libxslt-dev python3 python3-dev \
               wget mlocate build-essential openssh-client sshpass\
               nano cron yasm cmake libjpeg-dev autossh software-properties-common\
               libpng-dev libtiff-dev libavcodec-dev libavformat-dev \
               libswscale-dev libv4l-dev libxvidcore-dev libx264-dev python3-opencv libopencv-dev \
               libgtk-3-dev libatlas-base-dev gfortran libpq-dev curl fail2ban \
               ffmpeg  git-all libeigen3-dev pkg-config libssl-dev zlib1g unzip \
               && rm -rf /var/lib/apt/lists/*

WORKDIR /NNvision

# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py

RUN pip install psutil Pillow requests onvif_zeep-roboticia cherrypy python-crontab websockets httpx filelock \
                opencv-python opencv-contrib-python

# Install WSDiscovery from source because we need latest version
RUN git clone https://github.com/andreikop/python-ws-discovery.git && cd python-ws-discovery && \
    python3 setup.py install

# get tkDNN
git clone https://github.com/jouvencia/tkDNN.git

RUN git clone https://github.com/AlexeyAB/darknet

RUN cd  darknet  && \
	sed -i '1,10s/GPU=.*/GPU=1/' Makefile && \
	sed -i '1,10s/CUDNN=.*/CUDNN=1/' Makefile && \
	sed -i '1,10s/OPENCV=.*/OPENCV=1/' Makefile && \
	sed -i '1,10s/LIBSO=.*/LIBSO=1/' Makefile

# compile darknet


